# Generated by Django 5.2.4 on 2025-07-15 11:30

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "products",
            "0002_alter_color_hex_code_alter_color_slug_alter_fit_name_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "street_address1",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "street_address2",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "town_or_city",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("county", models.CharField(blank=True, max_length=80, null=True)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StyleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "belt_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="belt_size_profiles",
                        to="products.size",
                    ),
                ),
                (
                    "fit_preference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.fit",
                    ),
                ),
                (
                    "jacket_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jacket_size_profiles",
                        to="products.size",
                    ),
                ),
                (
                    "occasion_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occasion1_profiles",
                        to="products.occasion",
                    ),
                ),
                (
                    "occasion_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occasion2_profiles",
                        to="products.occasion",
                    ),
                ),
                (
                    "occasion_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occasion3_profiles",
                        to="products.occasion",
                    ),
                ),
                (
                    "preferred_color_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_color1_profiles",
                        to="products.color",
                    ),
                ),
                (
                    "preferred_color_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_color2_profiles",
                        to="products.color",
                    ),
                ),
                (
                    "preferred_color_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_color3_profiles",
                        to="products.color",
                    ),
                ),
                (
                    "shirt_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shirt_size_profiles",
                        to="products.size",
                    ),
                ),
                (
                    "trousers_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trousers_size_profiles",
                        to="products.size",
                    ),
                ),
                (
                    "waistcoat_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waistcoat_size_profiles",
                        to="products.size",
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_profile",
                        to="user.userprofile",
                    ),
                ),
            ],
        ),
    ]
