# Generated by Django 5.2.4 on 2025-07-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="hex_code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="color",
            name="slug",
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fit",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fit",
            name="slug",
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="kind",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
